[package]
name = "rest-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.7"
serde = "1.0.210"
serde_json = "1.0.68"
tokio = "1.40.0"
