[package]
name = "rest-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.7"
log = "0.4.22"
pretty_env_logger = "0.5.0"
serde = "1.0.210"
serde_json = "1.0.68"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
