[package]
name = "rest-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#axum = { version = "0.7.7", features = [] }
axum = { version = "0.7.7", features = ["multipart", "tokio", "ws"] }
config = "0.14.0"
const_format = "0.2.33"
fast_config = { path = "../fast_config", features = ["toml"] }
lazy_static = "1.5.0"
log = "0.4.22"
sensible-env-logger = "0.3.2"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.40", features = ["rt", "rt-multi-thread", "sync", "time", "macros"] }

[dev-dependencies]
axum-extra = { version = "0.9", features = ["cookie", "typed-routing", "query"] }
axum-msgpack = "0.4"
axum-yaml = "0.4"
futures-util = "0.3"

axum-test = {version = "16.2.0"}
rstest = "0.23.0"
